language: java
jdk: openjdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - mvn clean install
after_success:
  - mvn -DrepoToken=$TOKEN jacoco:report coveralls:report
notifications:
  email:
    on_success: never
    on_failure: never
